### ISSUE TITLE
Count ?

### ISSUE THREAD

**Issue by mmmcorpsvit** [kolypto/py-jessiql#1]
in MongoQuery present count:1 param, what can use now?

**Comment by kolypto** [comment]
Hi @mmmcorpsvit , thanks for your interest in JessiQL :) it's under development so the docs aren't ready yet, sorry :) 

You use `Query.count()` instead of `Query.fetchall()` and then you get the count. This requires an additional line of code from the back-end developer :) 

I've made a decision to remove aggregation, including counts, from JessiQL because such behavior breaks API schema. That is, if an API returns a list of objects, `{count: 1}` will modify the shape of the response into an integer. This is quite unacceptable in our modern age of OpenAPI and GraphQL :)

**Comment by mmmcorpsvit** [comment]
i use FastAPI and in Response model simple write: [MyModelResponse | QBCountResponse | Any]
not very big problem, but think you right)

th for great library
